s3:
    # https://wasabi.com/
    access_key_id: "YOUR_ACCESS_KEY_ID"
    secret_access_key: "YOUR_SECRET_ACCESS_KEY"
    default_bucket: "bills"
    endpoint: "https://s3.wasabisys.com"
    region: "us-east-1"
congress:
    # https://api.congress.gov/sign-up/
    # 6 Keys Works Fine Without Stopping
    keys:
        - "YOUR_FIRST_API_KEY"
        - "YOUR_SECOND_API_KEY"
        - "YOUR_THIRD_API_KEY"
mysql:
    hostname: "localhost"
    username: "root"
    password: ""
    database: "congress"
activitypub:
    hostname: "localhost"
    server_port: 8080
    account_name: "demo"
    web_hostname: "localhost"
    web_domain: "http://localhost"
    certificate_path: "/etc/letsencrypt/live/.../fullchain.pem"
    private_key_path: "/etc/letsencrypt/live/.../privkey.pem"
    activitypub_public_key: "-----BEGIN PUBLIC KEY-----\n...\n-----END PUBLIC KEY-----"
    activitypub_private_key: "-----BEGIN RSA PRIVATE KEY-----\n...\n-----END RSA PRIVATE KEY-----"
    logo: "../images/logo.png"
    header: "../images/header.png"
    emoji: "../images/bill-emoji.png"
