s3:
    # https://wasabi.com/
    access_key_id: "YOUR_ACCESS_KEY_ID"
    secret_access_key: "YOUR_SECRET_ACCESS_KEY"
    default_bucket: "bills"
    endpoint: "https://s3.wasabisys.com"
    region: "us-east-1"
congress:
    # https://api.congress.gov/sign-up/
    # 6 Keys Works Fine Without Stopping
    keys:
        - "YOUR_FIRST_API_KEY"
        - "YOUR_SECOND_API_KEY"
        - "YOUR_THIRD_API_KEY"
